@ECHO OFF
COPY /Y JAVA.MOO JAVA.BKP >NUL
TYPE SRC\MAIN.MOO >>JAVA.MOO
TYPE SRC\CMD.MOO >>JAVA.MOO
TYPE SRC\CRC16.MOO >>JAVA.MOO
TYPE SRC\ZIP.MOO >>JAVA.MOO
TYPE SRC\CLASSF.MOO >>JAVA.MOO
TYPE SRC\CPOOL.MOO >>JAVA.MOO
TYPE SRC\METHOD.MOO >>JAVA.MOO
TYPE SRC\OPCODE.MOO >>JAVA.MOO
TYPE SRC\PROCESS.MOO >>JAVA.MOO
ECHO Building JAVA.COM...
MRC.EXE JAVA.MOO >JAVA.LOG
DIR JAVA.COM
COPY /Y JAVA.BKP JAVA.MOO >NUL
