@ECHO OFF
COPY /Y JAVA.MOO JAVA.BKP
TYPE SRC\MAIN.MOO >>JAVA.MOO
TYPE SRC\CMD.MOO >>JAVA.MOO
TYPE SRC\CRC16.MOO >>JAVA.MOO
TYPE SRC\ZIP.MOO >>JAVA.MOO
TYPE SRC\CLASSF.MOO >>JAVA.MOO
TYPE SRC\CPOOL.MOO >>JAVA.MOO
TYPE SRC\METHOD.MOO >>JAVA.MOO
TYPE SRC\OPCODE.MOO >>JAVA.MOO
TYPE SRC\PROCESS.MOO >>JAVA.MOO
MRC.EXE JAVA.MOO
COPY /Y JAVA.BKP JAVA.MOO
REM JAVA -classpath NATIVE.JAR;HELLO.JAR Hello
JAVA -classpath NATIVE.JAR;UTILS.JAR;SHELL.JAR Shell
