%MAX_METHOD_CACHE = 100

DIM METHOD_CACHE_CRC%[%MAX_METHOD_CACHE]
DIM METHOD_CACHE_FILE_IDX%[%MAX_METHOD_CACHE]
DIM METHOD_CACHE_POS&[%MAX_METHOD_CACHE]
DIM METHOD_CACHE_LEN%[%MAX_METHOD_CACHE]
DIM METHOD_CACHE_COUNT%
DIM METHOD_CACHE_IDX%

SUB SearchMethodCode(FileHandle%, JarIdx%,MethodSignature$)
