DIM METHOD_CACHE_CRC%[100]
DIM METHOD_CACHE_FILE_IDX%[100]
DIM METHOD_CACHE_POS&[100]
DIM METHOD_CACHE_LEN%[100]
DIM METHOD_CACHE_IDX%

SUB SearchMethodCode(FileHandle%, JarIdx%,MethodSignature$)
