%OPCODE_ICONST_0 = 3
%OPCODE_ICONST_1 = 4
%OPCODE_ICONST_2 = 5
%OPCODE_ICONST_3 = 6
%OPCODE_ICONST_4 = 7
%OPCODE_ICONST_5 = 8
%OPCODE_LDC = 18
%OPCODE_ILOAD = 21
%OPCODE_ALOAD_0 = 42
%OPCODE_ALOAD_1 = 43
%OPCODE_ALOAD_2 = 44
%OPCODE_ALOAD_3 = 45
%OPCODE_BALOAD = 51
%OPCODE_ISTORE = 54
%OPCODE_ASTORE_0 = 75
%OPCODE_ASTORE_1 = 76
%OPCODE_ASTORE_2 = 77
%OPCODE_ASTORE_3 = 78
%OPCODE_POP = 87
%OPCODE_IINC = 132
%OPCODE_IFEQ = 153
%OPCODE_IFNE = 154
%OPCODE_IF_ICMPEQ = 159
%OPCODE_IF_ICMPLT = 161
%OPCODE_IF_ACMPEQ = 165
%OPCODE_IF_ACMPNE = 166
%OPCODE_GOTO = 167
%OPCODE_IRETURN = 172
%OPCODE_RETURN = 177
%OPCODE_INVOKE_STATIC = 184
%OPCODE_ARRAYLENGTH = 190

%MAX_STACK = 10
%MAX_LOCALS = 10

%STACK_ENTRY_SIZE = 3
%LOCALS_ENTRY_SIZE = 3

%TYPE_INT = 0
%TYPE_REF = 1

DIM CODE_OFFSET%

DIM StackValue%
DIM StackValue$
DIM LocalValue%
DIM LocalValue$

SUB RunCode(F%, MethodIdx%, Offset%)
SUB StackPush(Value%, StackType@)
SUB StackPushString(Value$)
SUB StackPop()
SUB StackPopString()
SUB LocalSet(Index%, Value%, LocalsType@)
SUB LocalSetString(Index%, Value$)
SUB LocalGet(Index%)
SUB LocalGetString(Index%)
