
%OPCODE_ACONST_NULL = 1
%OPCODE_ICONST_0 = 3
%OPCODE_ICONST_1 = 4
%OPCODE_ICONST_2 = 5
%OPCODE_ICONST_3 = 6
%OPCODE_ICONST_4 = 7
%OPCODE_ICONST_5 = 8
%OPCODE_BIPUSH = 16
%OPCODE_SIPUSH = 17
%OPCODE_LDC = 18
%OPCODE_ILOAD = 21
%OPCODE_ALOAD = 25
%OPCODE_ILOAD_0 = 26
%OPCODE_ILOAD_1 = 27
%OPCODE_ILOAD_2 = 28
%OPCODE_ILOAD_3 = 29
%OPCODE_ALOAD_0 = 42
%OPCODE_ALOAD_1 = 43
%OPCODE_ALOAD_2 = 44
%OPCODE_ALOAD_3 = 45
%OPCODE_IALOAD = 46
%OPCODE_BALOAD = 51
%OPCODE_ISTORE = 54
%OPCODE_ASTORE = 58
%OPCODE_ISTORE_0 = 59
%OPCODE_ISTORE_1 = 60
%OPCODE_ISTORE_3 = 61
%OPCODE_ISTORE_4 = 62
%OPCODE_ASTORE_0 = 75
%OPCODE_ASTORE_1 = 76
%OPCODE_ASTORE_2 = 77
%OPCODE_ASTORE_3 = 78
%OPCODE_IASTORE = 79
%OPCODE_BASTORE = 84
%OPCODE_POP = 87
%OPCODE_DUP = 89
%OPCODE_IADD = 96
%OPCODE_ISUB = 100
%OPCODE_IMUL = 104
%OPCODE_IINC = 132
%OPCODE_IFEQ = 153
%OPCODE_IFNE = 154
%OPCODE_IF_ICMPEQ = 159
%OPCODE_IF_ICMPNE = 160
%OPCODE_IF_ICMPLT = 161
%OPCODE_IF_ICMPGE = 162
%OPCODE_IF_ICMPGT = 163
%OPCODE_IF_ICMPLE = 164
%OPCODE_IF_ACMPEQ = 165
%OPCODE_IF_ACMPNE = 166
%OPCODE_GOTO = 167
%OPCODE_IRETURN = 172
%OPCODE_ARETURN = 176
%OPCODE_RETURN = 177
%OPCODE_INVOKE_VIRTUAL = 182
%OPCODE_INVOKE_STATIC = 184
%OPCODE_NEWARRAY = 188
%OPCODE_ARRAYLENGTH = 190

%ARRAY_TYPE_BOOLEAN = 4
%ARRAY_TYPE_CHAR = 5
%ARRAY_TYPE_FLOAT = 6
%ARRAY_TYPE_DOUBLE = 7
%ARRAY_TYPE_BYTE = 8
%ARRAY_TYPE_SHORT = 9
%ARRAY_TYPE_INT = 10
%ARRAY_TYPE_LONG = 11

%MAX_STACK = 10
%MAX_LOCALS = 10

%STACK_ENTRY_SIZE = 3
%LOCALS_ENTRY_SIZE = 3

%TYPE_NONE = -1
%TYPE_INT = 0
%TYPE_REF = 1
%TYPE_NULL = 2

DIM ParamTypes@[%MAX_LOCALS]
DIM Params%[%MAX_LOCALS]

DIM CODE_OFFSET%

DIM StackValue%
DIM STACK_TYPE%
DIM StackValue$
DIM LocalValue%
DIM LocalValue$

SUB RunCode(F%, MethodIdx%, Offset%)
SUB StackPush(Value%, StackType@)
SUB StackPushString(Value$)
SUB StackPop()
SUB StackPopString()
SUB LocalSet(Index%, Value%, LocalsType@)
SUB LocalSetString(Index%, Value$)
SUB LocalGet(Index%)
SUB LocalGetString(Index%)
