%OPCODE_LDC = 18
%OPCODE_ALOAD_1 = 43
%OPCODE_ASTORE_1 = 76
%OPCODE_IF_ACMPEQ = 165
%OPCODE_IF_ACMPNE = 166
%OPCODE_GOTO = 167
%OPCODE_INVOKE_STATIC = 184

%MAX_STACK = 10
%MAX_LOCALS = 10

DIM STACK$[%MAX_STACK]
DIM STACK_SIZE% = 0

DIM LOCALS$[%MAX_LOCALS]
DIM LOCALS_SIZE% = 0

DIM CODE_OFFSET% = 0

SUB RunCode(F%, MethodIdx%, Offset%)
