%MAX_PROCESS = 10

DIM PROCESS_FILE%[%MAX_PROCESS]
DIM PROCESS_METHOD%[%MAX_PROCESS]
DIM PROCESS_CODE_OFFSET%[%MAX_PROCESS]
DIM PROCESS_CODE_END%[%MAX_PROCESS]
DIM PROCESS_PARENT%[%MAX_PROCESS]
DIM PROCESS_STACK_PTR%[%MAX_PROCESS]
DIM PROCESS_LOCALS_PTR%[%MAX_PROCESS]
DIM PROCESS_IDLE%[%MAX_PROCESS]

DIM PROCESS_ID% = 0

SUB NewProcess(ClassName$, MethodDescription$, ParentId%)
SUB KillProcess(PID%)
