%MAX_PROCESS = 10

DIM PROCESS_FILE%[%MAX_PROCESS]
DIM PROCESS_CPOOL%[%MAX_PROCESS]
DIM PROCESS_METHOD%[%MAX_PROCESS]
DIM PROCESS_CODE_OFFSET%[%MAX_PROCESS]
DIM PROCESS_CODE_END%[%MAX_PROCESS]
DIM PROCESS_PARENT%[%MAX_PROCESS]
DIM PROCESS_STACK_PTR%[%MAX_PROCESS]
DIM PROCESS_LOCALS_PTR%[%MAX_PROCESS]
DIM PROCESS_IDLE%[%MAX_PROCESS]

DIM PROCESS_ID% = 0
DIM REF_USED% = 0

DIM STACK_MFREE_COUNT% = 0
DIM STACK_MFREE%[%MAX_STACK]

DIM LOCALS_MFREE_COUNT% = 0
DIM LOCALS_MFREE%[%MAX_LOCALS]

SUB NewProcess(ClassName$, MethodDescription$, ParentId%)
SUB KillProcess(PID%, ReturnType@, ReturnValue%)
SUB CheckRef(Ref%)
SUB SafeMFree(PTR_TO_FREE%)
